site_name: arc24
site_url: https://ironbar.github.io/arc24

# Configuration
theme:
  name: material
  language: en
  palette:
    primary: blue
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
  logo: res/arc_icon.jpg
  favicon: res/arc_icon.jpg

markdown_extensions:
  - admonition
  - pymdownx.tasklist
  - pymdownx.details
  - footnotes
  - tables
  - pymdownx.arithmatex:
      generic: true
  - mdx_truly_sane_lists

plugins:
    - search
    - awesome-pages
    - git-revision-date

extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/guillermobarbadillo/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/guille_bar
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCOHmUwHnd2hmUpiDzaQ1Isg
    - icon: fontawesome/brands/kaggle
      link: https://www.kaggle.com/ironbar
  # analytics:
  #   provider: google
  #   property: G-NH
repo_url: https://github.com/ironbar/arc24

extra_javascript:
  - javascript/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js